DROP TABLE IF EXISTS sticks;

CREATE TABLE sticks (
    id serial PRIMARY KEY,
    name varchar(100) NOT NULL,
    flex int NOT NULL,
    curve varchar(5) NOT NULL,
    agelevel varchar(25) NOT NULL,
    price decimal NOT NULL,
    purchaselink varchar(200) NOT NULL,
    image bytea
);

INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 77, 'P88', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 77, 'P14', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 77, 'P92', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 77, 'PM9', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 77, 'P28', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 87, 'P88', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 87, 'P14', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 87, 'P92', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 87, 'PM9', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 87, 'P28', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 95, 'P88', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 95, 'P14', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 95, 'P92', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 95, 'PM9', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 95, 'P28', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 102, 'P88', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 102, 'P14', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 102, 'P92', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 102, 'PM9', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor 1X Lite Grip', 102, 'P28', 'Senior', 224.99, 'https://www.purehockey.com/product/bauer-vapor-1x-lite-grip-composite-hockey-stick-senior/itm/29896-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 77, 'P28', 'Senior', 127.49, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-senior/itm/29897-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 77, 'P88', 'Senior', 127.49, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-senior/itm/29897-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 77, 'P92', 'Senior', 127.49, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-senior/itm/29897-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 87, 'P28', 'Senior', 127.49, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-senior/itm/29897-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 87, 'P88', 'Senior', 127.49, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-senior/itm/29897-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 87, 'P92', 'Senior', 127.49, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-senior/itm/29897-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 102, 'P28', 'Senior', 127.49, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-senior/itm/29897-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 102, 'P88', 'Senior', 127.49, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-senior/itm/29897-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 102, 'P92', 'Senior', 127.49, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-senior/itm/29897-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2700 Grip', 77, 'P28', 'Senior', 109.99, 'https://www.purehockey.com/product/bauer-nexus-n2700-grip-composite-hockey-stick-senior/itm/34032-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2700 Grip', 77, 'P88', 'Senior', 109.99, 'https://www.purehockey.com/product/bauer-nexus-n2700-grip-composite-hockey-stick-senior/itm/34032-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2700 Grip', 77, 'P92', 'Senior', 109.99, 'https://www.purehockey.com/product/bauer-nexus-n2700-grip-composite-hockey-stick-senior/itm/34032-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2700 Grip', 87, 'P28', 'Senior', 109.99, 'https://www.purehockey.com/product/bauer-nexus-n2700-grip-composite-hockey-stick-senior/itm/34032-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2700 Grip', 87, 'P88', 'Senior', 109.99, 'https://www.purehockey.com/product/bauer-nexus-n2700-grip-composite-hockey-stick-senior/itm/34032-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2700 Grip', 87, 'P92', 'Senior', 109.99, 'https://www.purehockey.com/product/bauer-nexus-n2700-grip-composite-hockey-stick-senior/itm/34032-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2700 Grip', 97, 'P28', 'Senior', 109.99, 'https://www.purehockey.com/product/bauer-nexus-n2700-grip-composite-hockey-stick-senior/itm/34032-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2700 Grip', 97, 'P88', 'Senior', 109.99, 'https://www.purehockey.com/product/bauer-nexus-n2700-grip-composite-hockey-stick-senior/itm/34032-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2700 Grip', 97, 'P92', 'Senior', 109.99, 'https://www.purehockey.com/product/bauer-nexus-n2700-grip-composite-hockey-stick-senior/itm/34032-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer NSX Grip', 60, 'P88', 'Intermediate', 59.99, 'https://www.purehockey.com/product/bauer-nsx-grip-composite-hockey-stick-intermediate/itm/34033-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer NSX Grip', 60, 'P92', 'Intermediate', 59.99, 'https://www.purehockey.com/product/bauer-nsx-grip-composite-hockey-stick-intermediate/itm/34033-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Team Grip', 65, 'P28', 'Intermediate', 149.99, 'https://www.purehockey.com/product/bauer-supreme-2s-team-grip-composite-hockey-stick-intermediate/itm/35623-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Team Grip', 65, 'P88', 'Intermediate', 149.99, 'https://www.purehockey.com/product/bauer-supreme-2s-team-grip-composite-hockey-stick-intermediate/itm/35623-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Team Grip', 65, 'P92', 'Intermediate', 149.99, 'https://www.purehockey.com/product/bauer-supreme-2s-team-grip-composite-hockey-stick-intermediate/itm/35623-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Pro Grip', 55, 'P14', 'Intermediate', 249.99, 'https://www.purehockey.com/product/bauer-supreme-2s-pro-grip-composite-hockey-stick-intermediate/itm/35545-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Pro Grip', 55, 'P28', 'Intermediate', 249.99, 'https://www.purehockey.com/product/bauer-supreme-2s-pro-grip-composite-hockey-stick-intermediate/itm/35545-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Pro Grip', 55, 'P88', 'Intermediate', 249.99, 'https://www.purehockey.com/product/bauer-supreme-2s-pro-grip-composite-hockey-stick-intermediate/itm/35545-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Pro Grip', 55, 'P92', 'Intermediate', 249.99, 'https://www.purehockey.com/product/bauer-supreme-2s-pro-grip-composite-hockey-stick-intermediate/itm/35545-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Pro Grip', 55, 'PM9', 'Intermediate', 249.99, 'https://www.purehockey.com/product/bauer-supreme-2s-pro-grip-composite-hockey-stick-intermediate/itm/35545-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Pro Grip', 65, 'P14', 'Intermediate', 249.99, 'https://www.purehockey.com/product/bauer-supreme-2s-pro-grip-composite-hockey-stick-intermediate/itm/35545-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Pro Grip', 65, 'P28', 'Intermediate', 249.99, 'https://www.purehockey.com/product/bauer-supreme-2s-pro-grip-composite-hockey-stick-intermediate/itm/35545-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Pro Grip', 65, 'P88', 'Intermediate', 249.99, 'https://www.purehockey.com/product/bauer-supreme-2s-pro-grip-composite-hockey-stick-intermediate/itm/35545-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Pro Grip', 65, 'P92', 'Intermediate', 249.99, 'https://www.purehockey.com/product/bauer-supreme-2s-pro-grip-composite-hockey-stick-intermediate/itm/35545-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Supreme 2S Pro Grip', 65, 'PM9', 'Intermediate', 249.99, 'https://www.purehockey.com/product/bauer-supreme-2s-pro-grip-composite-hockey-stick-intermediate/itm/35545-31/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 50, 'P28', 'Junior', 104.99, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-junior/itm/29897-21/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 50, 'P88', 'Junior', 104.99, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-junior/itm/29897-21/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X900 Lite Grip', 50, 'P92', 'Junior', 104.99, 'https://www.purehockey.com/product/bauer-vapor-x900-lite-grip-composite-hockey-stick-junior/itm/29897-21/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer NSX Grip', 40, 'P88', 'Junior', 49.99, 'https://www.purehockey.com/product/bauer-nsx-grip-composite-hockey-stick-junior/itm/34033-21/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer NSX Grip', 40, 'P92', 'Junior', 49.99, 'https://www.purehockey.com/product/bauer-nsx-grip-composite-hockey-stick-junior/itm/34033-21/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2900 Grip', 50, 'P28', 'Junior', 129.99, 'https://www.purehockey.com/product/bauer-nexus-n2900-grip-composite-hockey-stick-junior/itm/34031-21/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2900 Grip', 50, 'P88', 'Junior', 129.99, 'https://www.purehockey.com/product/bauer-nexus-n2900-grip-composite-hockey-stick-junior/itm/34031-21/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Nexus N2900 Grip', 50, 'P92', 'Junior', 129.99, 'https://www.purehockey.com/product/bauer-nexus-n2900-grip-composite-hockey-stick-junior/itm/34031-21/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer NSX Grip', 87, 'P88', 'Senior', 59.99, 'https://www.purehockey.com/product/bauer-nsx-grip-composite-hockey-stick-senior/itm/34033-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer NSX Grip', 87, 'P92', 'Senior', 59.99, 'https://www.purehockey.com/product/bauer-nsx-grip-composite-hockey-stick-senior/itm/34033-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X700 Lite Grip', 77, 'P28', 'Senior', 82.49, 'https://www.purehockey.com/product/bauer-vapor-x700-lite-grip-composite-hockey-stick-senior/itm/29898-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X700 Lite Grip', 77, 'P88', 'Senior', 82.49, 'https://www.purehockey.com/product/bauer-vapor-x700-lite-grip-composite-hockey-stick-senior/itm/29898-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X700 Lite Grip', 77, 'P92', 'Senior', 82.49, 'https://www.purehockey.com/product/bauer-vapor-x700-lite-grip-composite-hockey-stick-senior/itm/29898-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X700 Lite Grip', 87, 'P28', 'Senior', 82.49, 'https://www.purehockey.com/product/bauer-vapor-x700-lite-grip-composite-hockey-stick-senior/itm/29898-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X700 Lite Grip', 87, 'P88', 'Senior', 82.49, 'https://www.purehockey.com/product/bauer-vapor-x700-lite-grip-composite-hockey-stick-senior/itm/29898-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X700 Lite Grip', 87, 'P92', 'Senior', 82.49, 'https://www.purehockey.com/product/bauer-vapor-x700-lite-grip-composite-hockey-stick-senior/itm/29898-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X700 Lite Grip', 95, 'P28', 'Senior', 82.49, 'https://www.purehockey.com/product/bauer-vapor-x700-lite-grip-composite-hockey-stick-senior/itm/29898-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X700 Lite Grip', 95, 'P88', 'Senior', 82.49, 'https://www.purehockey.com/product/bauer-vapor-x700-lite-grip-composite-hockey-stick-senior/itm/29898-41/');
INSERT INTO sticks (name, flex, curve, agelevel, price, purchaselink) VALUES ('Bauer Vapor X700 Lite Grip', 95, 'P92', 'Senior', 82.49, 'https://www.purehockey.com/product/bauer-vapor-x700-lite-grip-composite-hockey-stick-senior/itm/29898-41/');